package constants

const (
	JWT_SECRET_KEY        = "JWT_SECRET"
	GOOGLE_CLIENT_ID      = "GOOGLE_CLIENT_ID"
	GOOGLE_CLIENT_SECRET  = "GOOGLE_CLIENT_SECRET"
	GOOGLE_REDIRECT_URL   = "GOOGLE_REDIRECT_URL"
	DATABASE_URL          = "DATABASE_URL"
	DB_HOST               = "DB_HOST"
	DB_PORT               = "DB_PORT"
	DB_USER               = "DB_USER"
	DB_PASSWORD           = "DB_PASSWORD"
	DB_NAME               = "DB_NAME"
	PORT                  = "PORT"
	ENCRYPTION_SECRET_KEY = "ENCRYPTION_SECRET_KEY"
)
